sudo: required

services:
- docker

language: generic

jobs:
  include:
    # Latest image build/push
    - if:  tag IS blank OR commit_message =~ /^Triggered by upstream build/
      script:
        - make build
      deploy:
        provider: script
        script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && make release
    # For release purpose
    - if: tag IS present AND commit_message !~ /^Triggered by upstream build/
      script:
        - make versioned && make test
      deploy:
        on:
          tags: true
        provider: script
        script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && make push-versioned